name: RoverProject

channels:
    - https://conda.anaconda.org/menpo
    - conda-forge

dependencies:
    - python==3.5.2
    - numpy
    - sympy
    - matplotlib
    - nb_conda
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.1.2
    - pip:
        - moviepy
